### PR TITLE
Fix flaky HeartbeatFromServerTest

### PR DESCRIPTION
**Pull request by puzpuzpuz**
* Fixes `warmUpConnectionToAddressWithRetry` handling in `HeartbeatFromServerTest`. Previous test implementation was leading to flakiness (e.g. see this [failed test](http://jenkins.hazelcast.com/job/NodeJS-pr-builder/558/testReport/junit/(root)/connectionRemoved%20fired%20when%20second%20member%20stops%20heartbeating/HeartbeatFromServerTest_connectionRemoved_fired_when_second_member_stops_heartbeating/))
* Also includes minor code style improvements

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
verify

**Comment by puzpuzpuz** [comment]
verify

**Comment by puzpuzpuz** [comment]
verify

**Comment by puzpuzpuz** [comment]
verify

**Comment by puzpuzpuz** [comment]
verify

**Review by mdumandag — APPROVED** [review]

**Pull request merged**
