### PR TITLE
Fix error message on failure to connect to include addresses

### PR DESCRIPTION
**Pull request by blicksky**
Linting and all tests pass. I manually verified that the error message has been corrected as shown in ClusterServiceTest "should throw with wrong host address in config".

### CODE REVIEW

**Comment by gAmUssA** [comment]
@blicksky could you add test?

**Comment by blicksky** [comment]
I updated the test I referenced to assert that the thrown error contains each of the addresses to which the client failed to connect.

**Comment by blicksky** [comment]
What I've submitted so far isn't quite right... the test assumes that hosts are IPv4 addresses, and nothing else in the codebase makes that assumption. I'll work on a change to clean that up.

**Comment by blicksky** [comment]
Ok, I updated the test. Let me know what you think of the approach.

**Comment by gAmUssA** [comment]
verify

**Comment by gAmUssA** [comment]
@blicksky kindly review and sign a contributor agreement https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by blicksky** [comment]
Signed contributor agreement sent to info@hazelcast.com.

**Comment by gAmUssA** [comment]
👍 
@GhostInAMachine @mustafaiman please, review and merge

**Comment by blicksky** [comment]
fixes #146

**Pull request merged**
