### PR TITLE
Implemented custom authentication

### PR DESCRIPTION
**Pull request by GhostInAMachine**

### CODE REVIEW

**Comment by gAmUssA** [comment]
@GhostInAMachine kindly, add tests

**Comment by GhostInAMachine** [comment]
Custom auth requires enterprise at the server side. Also, there's quite a lot of setup involved, custom auth object, this and that. So it cannot be automated.

**Comment by gAmUssA** [comment]
@GhostInAMachine is it backward compatible with group+pass auth?

**Comment by GhostInAMachine** [comment]
Regular auth can still be used without a problem. Is that what you mean?

**Comment by jackspaniel** [comment]
Thanks a lot guys. I will try this out next week with our COSC team and let you know if it works.

**Comment by gAmUssA** [comment]
@jackspaniel ping us in gitter then.

**Pull request merged**
