### PR TITLE
add missing config properties tests

### PR DESCRIPTION
**Pull request by mdumandag**
There were missing tests for the newly added properties.  This pr adds tests for these properties

### CODE REVIEW

**Comment by mustafaiman** [comment]
There is https://github.com/hazelcast/hazelcast-nodejs-client/pull/364/files for some time. The author of that PR is still responsive. Can you coordinate with him to merge his PR if possible? I would not want to disregard a community effort because we were not responsive enough.

**Comment by mdumandag** [comment]
Sorry, I didn't see that pr. I will communicate with him

**Comment by puzpuzpuz** [comment]
verify

**Comment by mdumandag** [comment]
verify

**Comment by mdumandag** [comment]
verify

**Comment by mdumandag** [comment]
verify

**Comment by mdumandag** [comment]
verify

**Comment by mdumandag** [comment]
verify

**Pull request merged**
