### PR TITLE
Add test to verify that member list is not broken after hot restart

### LINKED ISSUE #564: Verify that client member list state isn't broken with hot restart
4.0 version of the client shouldn't be affected by #472, but we need to verify that with a new test.

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Closes #564

* Adds `ClientHotRestartEventTest` to verify correct behavior of the client after cluster restart when Hot Restart is in use
* Updates RC version and thrift generated code to `0.8-SNAPSHOT`
* Improves code style in tests and `ClientConnectionManager`
* Migrates `AutoPipeliningDisabledTest` to async/await

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
verify

**Comment by puzpuzpuz** [comment]
verify

**Comment by puzpuzpuz** [comment]
verify

**Comment by puzpuzpuz** [comment]
verify

**Review by mdumandag — APPROVED** [review]

**Pull request merged**
